# Generated by Django 3.2 on 2022-01-03 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='parent_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.article'),
        ),
    ]
