# Generated by Django 3.2 on 2022-01-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220103_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecguser',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='ecguser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='ecguser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
