# Generated by Django 3.2 on 2022-01-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_ecguser_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecguser',
            name='login',
            field=models.CharField(default='login', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
