# Generated by Django 3.2 on 2022-01-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_ecguser_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecguser',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='ecguser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='ecguser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
